name: Caliper test
version: "2.0.0"

caliper:
  blockchain: fabric

channels:
  - channelName: mychannel
    contracts:
      - id: basic
    

organizations:
  - mspid: Org1MSP
    identities:
      certificates:
        - name: "User1"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem"
        - name: "User2"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User2@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User2@org1.example.com/msp/signcerts/User2@org1.example.com-cert.pem"
        - name: "User3"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User3@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User3@org1.example.com/msp/signcerts/User3@org1.example.com-cert.pem"
        - name: "User4"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User4@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User4@org1.example.com/msp/signcerts/User4@org1.example.com-cert.pem"
        - name: "User5"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User5@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User5@org1.example.com/msp/signcerts/User5@org1.example.com-cert.pem"
        - name: "User6"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User6@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User6@org1.example.com/msp/signcerts/User6@org1.example.com-cert.pem"
        - name: "User7"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User7@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User7@org1.example.com/msp/signcerts/User7@org1.example.com-cert.pem"
        - name: "User8"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User8@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User8@org1.example.com/msp/signcerts/User8@org1.example.com-cert.pem"
        - name: "User9"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User9@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User9@org1.example.com/msp/signcerts/User9@org1.example.com-cert.pem"
        - name: "User10"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User10@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User10@org1.example.com/msp/signcerts/User10@org1.example.com-cert.pem"
        - name: "User11"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User11@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User11@org1.example.com/msp/signcerts/User11@org1.example.com-cert.pem"
        - name: "User12"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User12@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User12@org1.example.com/msp/signcerts/User12@org1.example.com-cert.pem"
        - name: "User13"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User13@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User13@org1.example.com/msp/signcerts/User13@org1.example.com-cert.pem"
        - name: "User14"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User14@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User14@org1.example.com/msp/signcerts/User14@org1.example.com-cert.pem"
        - name: "User15"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User15@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User15@org1.example.com/msp/signcerts/User15@org1.example.com-cert.pem"
        - name: "User16"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User16@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User16@org1.example.com/msp/signcerts/User16@org1.example.com-cert.pem"
        - name: "User17"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User17@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User17@org1.example.com/msp/signcerts/User17@org1.example.com-cert.pem"
        - name: "User18"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User18@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User18@org1.example.com/msp/signcerts/User18@org1.example.com-cert.pem"
        - name: "User19"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User19@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User19@org1.example.com/msp/signcerts/User19@org1.example.com-cert.pem"
        - name: "User20"
          clientPrivateKey:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User20@org1.example.com/msp/keystore/priv_sk"
          clientSignedCert:
            path: "../crypto-config/peerOrganizations/org1.example.com/users/User20@org1.example.com/msp/signcerts/User20@org1.example.com-cert.pem"

    peers:
      - peer0.org1.example.com:
        endpoint: "127.0.0.1:7051"
        tlsCACerts:
          path: "../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt"
          gprcOptions:
            "ssl-target-name-override": "peer0.org1.example.com"
            "grpc.keepalive_timeout_ms": 60000
            "grpc.keepalive_time_ms": 60000
      - peer1.org1.example.com:
        endpoint: "127.0.0.1:7053"
        tlsCACerts:
          path: "../crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt"
          gprcOptions:
            "ssl-target-name-override": "peer1.org1.example.com"
            "grpc.keepalive_timeout_ms": 60000
            "grpc.keepalive_time_ms": 60000
      - peer2.org1.example.com:
        endpoint: "127.0.0.1:7055"
        tlsCACerts:
          path: "../crypto-config/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/ca.crt"
          gprcOptions:
            "ssl-target-name-override": "peer2.org1.example.com"
            "grpc.keepalive_timeout_ms": 60000
            "grpc.keepalive_time_ms": 60000
      - peer3.org1.example.com:
        endpoint: "127.0.0.1:7057"
        tlsCACerts:
          path: "../crypto-config/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/ca.crt"
          gprcOptions:
            "ssl-target-name-override": "peer3.org1.example.com"
            "grpc.keepalive_timeout_ms": 60000
            "grpc.keepalive_time_ms": 60000
      - peer4.org1.example.com:
        endpoint: "127.0.0.1:7059"
        tlsCACerts:
          path: "../crypto-config/peerOrganizations/org1.example.com/peers/peer4.org1.example.com/tls/ca.crt"
          gprcOptions:
            "ssl-target-name-override": "peer4.org1.example.com"
            "grpc.keepalive_timeout_ms": 60000
            "grpc.keepalive_time_ms": 60000
    orderers:
      - orderer.example.com:
        endpoint: "127.0.0.1:6050"
        tlsCACerts:
          path: "../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt"
          gprcOptions:
            "ssl-target-name-override": "orderer.example.com"
            "grpc.keepalive_timeout_ms": 60000
            "grpc.keepalive_time_ms": 60000
      - orderer2.example.com:
        endpoint: "127.0.0.1:6051"
        tlsCACerts:
          path: "../crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/ca.crt"
          gprcOptions:
            "ssl-target-name-override": "orderer1.example.com"
            "grpc.keepalive_timeout_ms": 60000
            "grpc.keepalive_time_ms": 60000
      - orderer3.example.com:
        endpoint: "127.0.0.1:6052"
        tlsCACerts:
          path: "../crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/ca.crt"
          gprcOptions:
            "ssl-target-name-override": "orderer2.example.com"
            "grpc.keepalive_timeout_ms": 60000
            "grpc.keepalive_time_ms": 60000
      - orderer4.example.com:
        endpoint: "127.0.0.1:6053"
        tlsCACerts:
          path: "../crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/ca.crt"
          gprcOptions:
            "ssl-target-name-override": "orderer3.example.com"
            "grpc.keepalive_timeout_ms": 60000
            "grpc.keepalive_time_ms": 60000
      # - orderer5.example.com:
      #   endpoint: "127.0.0.1:6054"
      #   tlsCACerts:
      #     path: "../crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/ca.crt"
      #     gprcOptions:
      #       "ssl-target-name-override": "orderer4.example.com"
      #       "grpc.keepalive_timeout_ms": 60000
      #       "grpc.keepalive_time_ms": 60000
